@echo off
REM ****************************************************************************
REM Vivado (TM) v2020.2 (64-bit)
REM
REM Filename    : simulate.bat
REM Simulator   : Xilinx Vivado Simulator
REM Description : Script for simulating the design by launching the simulator
REM
REM Generated by Vivado on Mon Aug 09 21:32:17 -0500 2021
REM SW Build 3064766 on Wed Nov 18 09:12:45 MST 2020
REM
REM Copyright 1986-2020 Xilinx, Inc. All Rights Reserved.
REM
REM usage: simulate.bat
REM
REM ****************************************************************************
REM simulate design
echo "xsim testcase2_main_SIM_behav -key {Behavioral:sim_1:Functional:testcase2_main_SIM} -tclbatch testcase2_main_SIM.tcl -view C:/Users/iamcy/Box/Shanshan_Xie/Testing/2-2021Ising_FPGA/Ising_testing_FPGA/Ising_testcase1_init/testcase2_main_SIM_behav.wcfg -log simulate.log"
call xsim  testcase2_main_SIM_behav -key {Behavioral:sim_1:Functional:testcase2_main_SIM} -tclbatch testcase2_main_SIM.tcl -view C:/Users/iamcy/Box/Shanshan_Xie/Testing/2-2021Ising_FPGA/Ising_testing_FPGA/Ising_testcase1_init/testcase2_main_SIM_behav.wcfg -log simulate.log
if "%errorlevel%"=="0" goto SUCCESS
if "%errorlevel%"=="1" goto END
:END
exit 1
:SUCCESS
exit 0
